---
## Show the DNS records to configure with dkim publik key

- name: extract DKIM public key DNS record
  slurp:
    src: "{{ dkim_opendkim_config_dir }}/keys{{ '' if dkim_same_key else '/' ~ dkim_domain }}/{{ dkim_selector }}.txt"
  register: dkim_dns_record

- name: display DKIM public key DNS record
  debug:
    msg:
      - "################################################################################################"
      - "DNS record to add for zone {{ dkim_domain }}:"
      - "{{ dkim_dns_record.content | string | b64decode }}"
      - "################################################################################################"

- name: Create local dns files directory
  ansible.builtin.file:
    path: ./dns_records
    state: directory
  delegate_to: localhost
  when: dkim_generate_dns_files

- local_action:
    module: copy
    content: |
          ################################################################################################
          DNS record to add for zone {{ dkim_domain }}:
          {{ dkim_dns_record.content | string | b64decode }}
          ################################################################################################
    dest: ./dns_records/dns_record.{{ dkim_domain }}
    backup: yes
  when: dkim_generate_dns_files

...
