---
## Show the DNS records to configure with dkim publik key

- name: extract found files content
  slurp:
    src: "/etc/opendkim/keys{{ '' if dkim_same_key else '/' ~ dkim_domain }}/{{ dkim_selector }}.txt"
  register: dkim_dns_record

- pause:
    seconds: 1
    prompt: |
      ################################################################################################
      DNS record to add for zone {{ dkim_domain }}:
      {{ dkim_dns_record.content | string | b64decode }}
      ################################################################################################

...
