---
## DKIM role's handlers

- name: restart opendkim
  service:
    name: opendkim
    state: restarted

- name: opendkim - restart postfix
  service:
    name: postfix
    state: restarted

- name: opendkim - restart sendmail
  systemd:
    name: sendmail
    state: restarted

- name: opendkim - refresh sendmail
  shell: make -C {{ dkim_sendmail_config_folder }}/
  notify: opendkim - restart sendmail

...
